// @ts-check
import sitemap from '@astrojs/sitemap';
import { defineConfig, fontProviders } from 'astro/config';

export default defineConfig({
	output: 'static',
	site: 'https://hikmah.pages.dev',
	integrations: [sitemap()],
	fonts: [
		{
			name: 'Noto Serif Myanmar',
			cssVariable: '--font-myanmar-serif',
			provider: fontProviders.google(),
			weights: [400, 500, 600, 700],
			styles: ['normal'],
			subsets: ['myanmar'],
			fallbacks: ['serif'],
		},
		{
			name: 'Noto Sans Myanmar',
			cssVariable: '--font-myanmar-sans',
			provider: fontProviders.google(),
			weights: ['400 700'],
			styles: ['normal'],
			subsets: ['myanmar'],
			fallbacks: ['sans-serif'],
		},
		{
			name: 'Noto Naskh Arabic',
			cssVariable: '--font-arabic',
			provider: fontProviders.google(),
			weights: ['400 700'],
			styles: ['normal'],
			subsets: ['arabic'],
			fallbacks: ['serif'],
		},
		{
			name: 'Noto Serif',
			cssVariable: '--font-serif',
			provider: fontProviders.google(),
			weights: ['400 700'],
			styles: ['normal'],
			fallbacks: ['serif'],
		},
		{
			name: 'Noto Sans',
			cssVariable: '--font-sans',
			provider: fontProviders.google(),
			weights: ['400 700'],
			styles: ['normal'],
			fallbacks: ['sans-serif'],
		},
		{
			name: 'Noto Sans Mono',
			cssVariable: '--font-mono',
			provider: fontProviders.google(),
			weights: ['400 700'],
			styles: ['normal'],
			fallbacks: ['monospace'],
		},
		{
			name: 'Material Symbols Outlined',
			cssVariable: '--font-icons',
			provider: fontProviders.googleicons(),
			weights: ['400 700'],
			styles: ['normal'],
			fallbacks: ['sans-serif'],
			options: {
				experimental: {
					glyphs: [
						'menu',
						'home',
						'search',
						'play_arrow',
						'pause',
						'book',
						'favorite',
						'volume_up',
						'arrow_back',
						'arrow_forward',
						'dark_mode',
						'light_mode',
						'close',
						'list',
						'schedule',
						'check',
						'share',
						'download',
						'link',
						'star',
					],
				},
			},
		},
	],
});
