import sitemap from "@astrojs/sitemap";
import { defineConfig, fontProviders } from "astro/config";

export default defineConfig({
	output: "static",
	site: "https://basirah.pages.dev",
	trailingSlash: "always",
	integrations: [sitemap()],
	fonts: [
		{
			name: "Noto Sans Myanmar",
			cssVariable: "--font-my",
			provider: fontProviders.google(),
			weights: ["400 700"],
			styles: ["normal"],
			subsets: ["myanmar"],
			fallbacks: ["sans-serif"],
		},
		{
			name: "Noto Naskh Arabic",
			cssVariable: "--font-ar",
			provider: fontProviders.google(),
			weights: ["400 700"],
			styles: ["normal"],
			subsets: ["arabic"],
			fallbacks: ["serif"],
		},
		{
			name: "Recursive",
			cssVariable: "--font-en",
			provider: fontProviders.google(),
			weights: ["400 700"],
			styles: ["normal"],
			subsets: ["latin"],
			fallbacks: ["sans-serif"],
			options: {
				experimental: {
					variableAxis: {
						MONO: [["0", "1"]],
						CASL: [["0", "1"]],
						CRSV: ["1"],
						slnt: [["-15", "0"]],
					},
				},
			},
		},
		{
			name: "Material Symbols Outlined",
			cssVariable: "--font-icon",
			provider: fontProviders.googleicons(),
			weights: [400],
			styles: ["normal"],
			fallbacks: ["sans-serif"],
			options: {
				experimental: {
					glyphs: [
						"arrow_back",
						"arrow_forward",
						"auto_awesome",
						"book",
						"chevron_left",
						"chevron_right",
						"close",
						"dark_mode",
						"favorite",
						"format_list_numbered",
						"home",
						"location_on",
						"light_mode",
						"menu",
						"menu_book",
						"pause",
						"play_arrow",
						"replay_10",
						"forward_10",
						"search",
						"search_off",
						"star",
						"translate",
						"volunteer_activism",
						"123",
					],
				},
			},
		},
	],
});
