// @ts-check
import sitemap from "@astrojs/sitemap";
import AstroPWA from "@vite-pwa/astro";
import { defineConfig, fontProviders } from "astro/config";

export default defineConfig({
	output: "static",
	site: "https://basirah.pages.dev",
	build: {
		inlineStylesheets: "always",
	},
	integrations: [
		sitemap(),
		AstroPWA({
			registerType: "autoUpdate",
			injectRegister: false,
			includeAssets: [
				"favicon.svg",
				"favicon.ico",
				"apple-touch-icon-180x180.png",
				"pwa-64x64.png",
				"pwa-192x192.png",
				"pwa-512x512.png",
				"maskable-icon-512x512.png",
			],
			manifest: {
				name: "Basirah — ကုရ်အာန်နှင့် စွန္နသ်မှ အသိပညာ ဗဟုသုတ",
				short_name: "Basirah",
				description:
					"Basirah ဝက်ဘ်ဆိုက်တွင် မရှိမဖြစ် စူရဟ်များ၊ ဒိုအာများနှင့် အလ္လာဟ်အရှင်မြတ်၏ အလှပဆုံး နာမတော်များကို မြန်မာဘာသာဖြင့် လေ့လာနိုင်ပါသည်။",
				lang: "my",
				start_url: "/",
				display: "standalone",
				theme_color: "#fdfbf7",
				background_color: "#fdfbf7",
				icons: [
					{
						src: "pwa-64x64.png",
						sizes: "64x64",
						type: "image/png",
					},
					{
						src: "pwa-192x192.png",
						sizes: "192x192",
						type: "image/png",
					},
					{
						src: "pwa-512x512.png",
						sizes: "512x512",
						type: "image/png",
					},
					{
						src: "maskable-icon-512x512.png",
						sizes: "512x512",
						type: "image/png",
						purpose: "maskable",
					},
				],
			},
			workbox: {
				navigateFallback: "/404",
				globPatterns: ["**/*.{js,css,html,woff2}"],
				cleanupOutdatedCaches: true,
			},
			experimental: {
				directoryAndTrailingSlashHandler: true,
			},
		}),
	],
	fonts: [
		{
			name: "Noto Serif Myanmar",
			cssVariable: "--font-myanmar-serif",
			provider: fontProviders.google(),
			weights: [400, 500, 600, 700],
			styles: ["normal"],
			subsets: ["myanmar"],
			fallbacks: ["serif"],
		},
		{
			name: "Noto Sans Myanmar",
			cssVariable: "--font-myanmar-sans",
			provider: fontProviders.google(),
			weights: ["400 700"],
			styles: ["normal"],
			subsets: ["myanmar"],
			fallbacks: ["sans-serif"],
		},
		{
			name: "Noto Naskh Arabic",
			cssVariable: "--font-arabic",
			provider: fontProviders.google(),
			weights: ["400 700"],
			styles: ["normal"],
			subsets: ["arabic"],
			fallbacks: ["serif"],
		},
		{
			name: "Noto Serif",
			cssVariable: "--font-serif",
			provider: fontProviders.google(),
			weights: ["400 700"],
			styles: ["normal"],
			fallbacks: ["serif"],
		},
		{
			name: "Noto Sans",
			cssVariable: "--font-sans",
			provider: fontProviders.google(),
			weights: ["400 700"],
			styles: ["normal"],
			fallbacks: ["sans-serif"],
		},
		{
			name: "Noto Sans Mono",
			cssVariable: "--font-mono",
			provider: fontProviders.google(),
			weights: ["400 700"],
			styles: ["normal"],
			fallbacks: ["monospace"],
		},
		{
			name: "Material Symbols Outlined",
			cssVariable: "--font-icons",
			provider: fontProviders.googleicons(),
			weights: ["400 700"],
			styles: ["normal"],
			fallbacks: ["sans-serif"],
			options: {
				experimental: {
					glyphs: [
						"menu",
						"home",
						"search",
						"play_arrow",
						"pause",
						"book",
						"favorite",
						"volume_up",
						"arrow_back",
						"arrow_forward",
						"dark_mode",
						"light_mode",
						"close",
						"list",
						"schedule",
						"check",
						"share",
						"download",
						"link",
						"star",
						"chevron_right",
						"chevron_left",
						"translate",
						"location_on",
						"123",
						"format_list_numbered",
						"menu_book",
						"volunteer_activism",
						"auto_awesome",
					],
				},
			},
		},
	],
});
