import sitemap from "@astrojs/sitemap";
import { defineConfig, fontProviders } from "astro/config";

export default defineConfig({
	output: "static",
	site: "https://basirah.pages.dev",
	integrations: [sitemap()],
	fonts: [
		{
			name: "Noto Serif Myanmar",
			cssVariable: "--font-myanmar-serif",
			provider: fontProviders.google(),
			weights: [400, 700],
			styles: ["normal"],
			subsets: ["myanmar"],
			fallbacks: ["serif"],
		},
		{
			name: "Noto Sans Myanmar",
			cssVariable: "--font-myanmar-sans",
			provider: fontProviders.google(),
			weights: ["400 700"],
			styles: ["normal"],
			subsets: ["myanmar"],
			fallbacks: ["sans-serif"],
		},
		{
			name: "Noto Naskh Arabic",
			cssVariable: "--font-arabic",
			provider: fontProviders.google(),
			weights: ["400 700"],
			styles: ["normal"],
			subsets: ["arabic"],
			fallbacks: ["serif"],
		},
		{
			name: "Noto Serif",
			cssVariable: "--font-serif",
			provider: fontProviders.google(),
			weights: ["400 700"],
			styles: ["normal"],
			fallbacks: ["serif"],
		},
		{
			name: "Noto Sans",
			cssVariable: "--font-sans",
			provider: fontProviders.google(),
			weights: ["400 700"],
			styles: ["normal"],
			fallbacks: ["sans-serif"],
		},
		{
			name: "Noto Sans Mono",
			cssVariable: "--font-mono",
			provider: fontProviders.google(),
			weights: ["400 700"],
			styles: ["normal"],
			fallbacks: ["monospace"],
		},
		{
			name: "Material Symbols Outlined",
			cssVariable: "--font-icons",
			provider: fontProviders.googleicons(),
			weights: [400],
			styles: ["normal"],
			fallbacks: ["sans-serif"],
			options: {
				experimental: {
					glyphs: [
						"arrow_back",
						"arrow_forward",
						"auto_awesome",
						"book",
						"chevron_left",
						"chevron_right",
						"close",
						"dark_mode",
						"favorite",
						"format_list_numbered",
						"home",
						"location_on",
						"light_mode",
						"menu",
						"menu_book",
						"pause",
						"play_arrow",
						"search",
						"search_off",
						"star",
						"translate",
						"volunteer_activism",
						"123",
					],
				},
			},
		},
	],
});
