// Generates public/_headers with a Content-Security-Policy whose sha256 hash
// is computed from the inline theme-bootstrap script in Layout.astro.
//
// The generated file is part of the Cloudflare Pages deploy artifact. Keeping
// the hash derived from the source avoids a security-sensitive manual step.

import { createHash } from "node:crypto";
import { readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";

const root = fileURLToPath(new URL("../", import.meta.url));
const layoutPath = `${root}src/layouts/Layout.astro`;
const layout = readFileSync(layoutPath, "utf8");

const match = layout.match(/<script is:inline>([\s\S]*?)<\/script>/);
if (!match) {
	throw new Error(
		"generate-headers: could not find the inline theme script in Layout.astro",
	);
}

const scriptBody = match[1];
if (!scriptBody) {
	throw new Error(
		"generate-headers: inline theme script body is empty in Layout.astro",
	);
}

const hash =
	"sha256-" + createHash("sha256").update(scriptBody).digest("base64");

const headers = `# Security headers — GENERATED by scripts/generate-headers.mts.
# Do not edit by hand; the CSP sha256 hash is derived from the inline theme
# script in Layout.astro so it can never drift out of sync.
/*
  X-Content-Type-Options: nosniff
  Referrer-Policy: strict-origin-when-cross-origin
  X-Frame-Options: DENY
  Permissions-Policy: camera=(), microphone=(), geolocation=(), payment=(), usb=()
  Strict-Transport-Security: max-age=63072000; includeSubDomains; preload
  Content-Security-Policy: default-src 'self'; script-src 'self' '${hash}' https://static.cloudflareinsights.com/beacon.min.js; style-src 'self' 'unsafe-inline'; img-src 'self'; font-src 'self'; media-src 'self'; connect-src 'self' https://cloudflareinsights.com; object-src 'none'; base-uri 'self'; frame-ancestors 'none'; form-action 'self'
  X-Robots-Tag: index, follow, max-image-preview:large, max-snippet:-1, max-video-preview:-1

# The custom 404 page carries meta robots noindex; keep the header consistent
/404
  ! X-Robots-Tag

# Hashed build assets (scripts, styles, fonts, recitation audio) are immutable
/_astro/*
  Cache-Control: public, max-age=31536000, immutable

# The service worker must always be fetched fresh so updates propagate
/sw.js
  Cache-Control: no-cache

/manifest.webmanifest
  Cache-Control: public, max-age=86400

# Static HTML pages: short shared cache with stale-while-revalidate for repeat visits
/*.html
  Cache-Control: public, max-age=3600, stale-while-revalidate=86400
`;

const outPath = `${root}public/_headers`;
writeFileSync(outPath, headers);
console.log(`generate-headers: wrote ${outPath} with CSP hash ${hash}`);
